escambo/config/routes.rb
Escambo::Application.routes.draw do

  get "categories/index"

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    get "admins/index"
  end

  namespace :site do
    get 'home', to: 'home#index' ##quando for ../home acessa /home/index
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_detail, only: [:show]
    resources :categories, only:[:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions'
  }
  root :to => 'site/home#index'

end

escambo/app/models/ad.rb
class Ad < ActiveRecord::Base
  #Constants
  QTT_PER_PAGE = 6

  # Callbacks
  before_save :md_to_html

  #Assossiations 
  belongs_to :member
  belongs_to :category, counter_cache: true 
  has_many :comments

  #validates
  validates :title, :description_md, :description_short, :category, presence:true
  validates :picture, :finish_date, presence:true
  validates :price, numericality: { greater_than: 0 }

  #scopes
  scope :descending_order, -> (page) {
   order(created_at: :desc).page(page).per(QTT_PER_PAGE) }

  scope :to_the, -> (member_id) { where(member_id: member_id) }

  scope :by_category, -> (id) { where(category_id: id) }

  scope :search, -> (term, page = 1) { 
    where("lower(title) LIKE?", "%#{term.downcase}%").page(page).per(QTT_PER_PAGE) }


  #paperclip
  has_attached_file :picture, styles: { large: "900x400#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  # gem money-rails
  monetize :price_cents

  attr_accessible :description,
                  :description_md,
                  :description_short,
                  :title,
                  :member,
                  :member_id,
                  :category,
                  :category_id,
                  :category_description,
                  :price,
                  :picture,
                  :finish_date,
                  :comment_id,
                  :comment


  private
    def md_to_html
      options = {
          filter_html: true,
          link_attributes: {
            rel: "nofollow",
            target: "_blank"
          }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)
      
      self.description = markdown.render(self.description_md)
    end

end

escambo/app/models/admin.rb
class Admin < ActiveRecord::Base
  #Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #Roles:
  #0 - full access
  #1 - restricted_access
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role

  # attr_accessible :title, :body

  def role_br
    if self.role == 0
     'full_access'
    else
     'restricted_access'
    end
  end

end

escambo/app/models/category.rb
class Category < ActiveRecord::Base
	# Gem Friendly Id
	include FriendlyId
	friendly_id :description, use: :slugged

  # Associations 
  has_many :ads

  #scopes
  scope :order_by_description, -> { order(:description) }

  attr_accessible :description, :ads_count, :slug
  validates_presence_of :description

end

escambo/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :member
  belongs_to :ad
  attr_accessible :body, :member_id, :ad_id
end

escambo/app/models/member.rb
class Member < ActiveRecord::Base

  has_many :ads
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :ads, :comments
  # attr_accessible :title, :body
end

escambo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Pundit
  include Pundit

  #Manage Pundit Errors
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIS, yout may want to use :null_session instead
  protect_from_forgery



  # Set Layout
  layout :layout_by_resource

  protected

    def layout_by_resource
      if devise_controller? && resource_name == :admin
        "backoffice_devise"
      elsif devise_controller? && resource_name == :member
        "site_devise"
      else
        "application"
      end
    end

    def user_not_authorized
      flash[:alert] = "Você não está autorizado a executar essa ação."
      redirect_to(request.referrer || root_path)
    end

end

escambo/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_filter :authenticate_admin!
  layout "backoffice"

  def pundit_user
    current_admin # current_user to Pundit
  end
end

escambo/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(params[:page])
  end
end

escambo/app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout "profile"

end

escambo/app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
	def ads
		@ads = Ad.search(params[:q], params[:page])
		@categories = Category.all
	end
end

escambo/app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"

end

escambo/app/helpers/ad_detail_helper.rb
module AdDetailHelper
end

escambo/app/helpers/application_helper.rb
module ApplicationHelper
end

escambo/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def option_for_roles
    roles = Admin.select(:role).uniq
    roles.each.map do |value|
      if value.role == 0
        OptionsForRoles.new(value.role, 'full_access')
      else
        OptionsForRoles.new(value.role, 'restricted_access')
      end
    end
  end
  # [0] #<Struct:OptionsForRoles:0x55dcc92d3dd0 description = "full_access", id = 0>
  # [1] #<Struct:OptionsForRoles:0x55dcc92d3d30 description = "restricted_access", id = 1>
end

escambo/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

escambo/app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

escambo/app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

escambo/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

escambo/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escambo/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escambo/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<!-- ## if devise_mapping.registerable? && controller_name != 'registrations'
# link_to "Sign up", new_registration_path(resource_name)
# end -->

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

escambo/app/views/backoffice/admins/shared/_form.html.erb
<%- model_class = Admin -%>
<h1 class="page-header"><%= model_class.model_name.human(count:2) %></h1>
<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @admin.errors.full_messages.each do |messages| %>
        <li><%= messages %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">
      <%= action %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="col-lg-6">
    <%= form_for([:backoffice, @admin]) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => "form-control", :placeholder => "Ex: João da Silma" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, :class => "form-control", :placeholder => "Ex: user@gmail.com" %>
        </div>

        <% if policy(Admin).edit? %>
          <div class="form-group">
            <%= f.label :role %>
            <br>
            <% option_for_roles.each do |v| %>
              <%= f.radio_button :role, v.id, :class => 'text_field' %> <%= t('activerecord.attributes.admin.access.'"#{v.description}") %>
              <br>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control", :placeholder => "*******" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "*******" %>
        </div>
        <button type="submit" class="btn btn-default">Salvar</button>
    <% end %>
    </div>
  </div>
  <!-- /.panel-body -->
</div>
<script>
  $()
</script>

escambo/app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, :class => 'form-control')%>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, :class => 'form-control') %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, :class => 'form-control') %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag t('buttons.send_message'), :class => 'btn btn-primary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

escambo/app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, :class => 'form-control')%>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, :class => 'form-control', :required => 'required') %>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, :class => 'form-control') %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag t('buttons.send_message'), :class => 'btn btn-primary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

escambo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escambo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

escambo/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BackOffice - Escambo</title>

    <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    "backoffice", :media => "all", 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="wrapper">
      <%= render partial: "layouts/backoffice_shared/navigation" %>
      <!-- Page Content -->
      <div id="page-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <%= yield %>
            </div>
            <!-- /.col-lg-12 -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- /#page-wrapper -->
    </div>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "backoffice" %>

    <%= render partial: "layouts/shared/notifications" %>

  </body>
</html>

escambo/app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>BackOffice - Escambo</title>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "backoffice", :media => "all", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "backoffice", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>

escambo/app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">BackOffice - Escamboapp</a>
  </div>
  <!-- /.navbar-header -->
  <ul class="nav navbar-top-links navbar-right">
    <!-- .dropdown -->
    <li><%= current_admin.email %></li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li class="divider"></li>
            <li>
              <%= link_to  destroy_admin_session_path, method: :delete do %>
                <i class="fa fa-sign-out fa-fw"></i>
                Sair
              <% end %>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <%= link_to backoffice_path do %>
            <i class="fa fa-dashboard fa-fw"></i> Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to backoffice_categories_path do %>
            <i class="fa fa-th-list fa-fw"></i> Categorias
          <% end %>
        </li>
        <li>
          <%= link_to backoffice_admins_index_path do %>
            <i class="fa fa-users fa-fw"></i> Administradores
          <% end %>
        </li>
        <% if Rails.env.development? %>
          <li>
            <%= link_to backoffice_diagrams_path do %>
              <i class="fa fa-database fa-fw"></i> Diagram ERD
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
      <!-- /.sidebar-collapse -->
  </div>
    <!-- /.navbar-static-side -->
</nav>

escambo/app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>EscamboApp</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "site", :media => "all" %>
  <%= stylesheet_link_tag    "site/profile", :media => "all" %>

  <%= csrf_meta_tags %>
  <!-- Bootstrap core CSS -->

  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <%= render partial: "layouts/site_shared/navigation" %>
  <div id="wrapper">

      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <li class="sidebar-brand">
                  <a href="#">
                      Start Bootstrap
                  </a>
              </li>
              <li>
                  <%= link_to "Dashboard", site_profile_dashboard_index_path %>
              </li>
              <li>
                  <%= link_to "Meus Anúncios", site_profile_ads_path %>
              </li>
              <li>
                  <%= link_to "Novo Anúncio", new_site_profile_ad_path %>
              </li>
          </ul>
      </div>
      <!-- /#sidebar-wrapper -->

      <!-- Page Content -->
      <div id="page-content-wrapper">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12">
                      <%= yield %>
                  </div>
              </div>
          </div>
      </div>
      <!-- /#page-content-wrapper -->

  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'site' %>
  <%= javascript_include_tag 'site/profile' %>

  <%#= javascript_include_tag 'site/profile/ads' %>
  <%= yield :javascripts %>

  <%= render partial: 'layouts/shared/notifications' %>

</body>

</html>

escambo/app/views/layouts/shared/_notifications.html.erb
<% if notice %>
  <%= javascript_tag "$.notify( { message: '#{notice}' }, { type: 'success', placement: { from: 'top', align: 'center' }});" %>
<% end %>
<% if alert %>
  <%= javascript_tag "$.notify( { message: '#{alert}' }, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
<% end %>

escambo/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>EscamboApp</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "site", :media => "all" %>

  <%= csrf_meta_tags %>
  <!-- Bootstrap core CSS -->

  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <div id="global-spin" class="loading" style="display:none">Loading&#8230;</div>
  <%= render partial: "layouts/site_shared/navigation" %>


  <!-- Page Content -->
  <div class="container">

    <%= form_tag  site_search_path, method: :get do %>
      <div class="row">
        <div class="well well-sm">
          <div class="row">
            <div class="col-lg-3"></div>  
            <div class="col-lg-6">
              <div class="input-group">
                <%= text_field_tag(:q, params[:q], { :class => "form-control", :placeholder => "Pesquisar por..."}) %>
                <span class="input-group-btn">
                  <%= submit_tag("Pesquisar", :class => "btn btn-default") %>
                </span>
              </div>
            </div>
            <div class="col-lg-3"></div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <%= render partial: 'layouts/site_shared/sidebar' %>
      <div id="home-detail" class="col-md-9">
        <% if controller_path == 'site/home' %>
          <%= render partial: 'layouts/site_shared/carousel' %>
        <% end %>
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>



  <%= render partial: "layouts/site_shared/footer" %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'site' %>
</body>

</html>

escambo/app/views/layouts/site_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Site - Escambo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "Site", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "Site" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>